name: bible_studies_wing
description: "a bible studies application for Methodist Wing"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ^3.8.1
#  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  expandable: ^5.0.1
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_quill: ^11.4.2
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  # intl: ^0.19.0
  # share_plus: ^7.0.2
  uuid: ^4.5.1
  get: ^4.7.2
  flutter_cache_manager: ^3.4.1
  backdrop: ^0.9.1
  get_storage: ^2.1.1
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

  http: any
  rxdart: any
  intl: any
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  flutter_swipe_detector: ^2.0.0
  flutter_app_badge_control: ^0.0.2
dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master # or 786d04363f587b818ce585d25b9c2bb62de95aba
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/cards/
    - assets/images/googleimage.png
    - assets/images/bslogo.jpg
    - assets/images/background.png

    # icons
    - assets/icons/megaphone.png
    - assets/icons/meeting.png

    # config
#    - assets/config/
