name: bible_studies_wing
description: "a bible studies application for Methodist Wing"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image:
  json_annotation: ^4.8.1
  expandable: ^5.0.1
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_quill: ^9.2.3
  google_sign_in: ^6.1.4
  image_picker: ^1.0.7
  # intl: ^0.19.0
  # share_plus: ^7.0.2
  uuid: ^4.3.3
  get: ^4.6.6
  flutter_cache_manager: ^3.3.1
  backdrop: ^0.9.1
  get_storage: ^2.1.1
  cloud_firestore:
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  path_provider:
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  dynamic_multi_step_form: ^1.1.3+3 

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/cards/
    - assets/images/googleimage.png
    - assets/images/bslogo.jpg
    - assets/images/background.png

    # icons
    - assets/icons/megaphone.png
    - assets/icons/meeting.png
