// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VOEe92c1LBVmfqSkciPkAJXKFXG--rc',
    appId: '1:93150933206:web:2375ad25f117dba150d977',
    messagingSenderId: '93150933206',
    projectId: 'biblestudywing-32f3b',
    authDomain: 'biblestudywing-32f3b.firebaseapp.com',
    storageBucket: 'biblestudywing-32f3b.appspot.com',
    measurementId: 'G-Y50V4HZJC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEJ4BNqiZX_rvUvmx-x3jtf-V-3F29sg',
    appId: '1:93150933206:android:fc1a1e418d5bfb7950d977',
    messagingSenderId: '93150933206',
    projectId: 'biblestudywing-32f3b',
    storageBucket: 'biblestudywing-32f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMaN7KB8dRCg8Pczy7iK4jFIsR2d7JvcM',
    appId: '1:93150933206:ios:87112107c8ce366a50d977',
    messagingSenderId: '93150933206',
    projectId: 'biblestudywing-32f3b',
    storageBucket: 'biblestudywing-32f3b.appspot.com',
    androidClientId: '93150933206-0lin8ti09tvaf457kmt5urj5reegh4u9.apps.googleusercontent.com',
    iosClientId: '93150933206-5chpp3g7n6qf6gdt2u58820b2ln486ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleStudiesWing',
  );

}